#pragma once

// GENERATED by tools/verified_addresses/gen_verified_addresses.py from
// tools/verified_addresses/spec.json. DO NOT EDIT BY HAND: change the spec and re-run
// (see Docs/VERIFIED-ADDRESSES.md, "Regenerating").
//
// One row per hook-critical / seat-critical Address Library id, per EXACT runtime. Each
// expected RVA was derived from our own copy of that executable (RTTI walk or a unique
// byte signature) and then matched against the Address Library for that build; the
// generator refuses to write this file if they disagree. REL::SelfCheck::Run() compares the
// library in use at runtime against these rows. See REL/SelfCheck.h.

#include "REL/SelfCheck.h"

namespace MFO::VerifiedAddresses
{
	// 1.6.1170.0: 55 rows
	inline constexpr REL::SelfCheck::Row kRows_1_6_1170[] = {
		{ 207886, 0x18A5558, 0x0, 0, {  }, "Targeting.Character.UpdateCombat" },
		{ 208040, 0x18AB9C0, 0x0, 0, {  }, "MainThread.PlayerCharacter.Update" },
		{ 205828, 0x187B8B0, 0x0, 0, {  }, "CasterConsent.ActorMagicCaster.CheckCast" },
		{ 211104, 0x18CC4A0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterOffensive.CheckStartCast" },
		{ 211142, 0x18CC890, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterRestore.CheckStartCast" },
		{ 211118, 0x18CC638, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterWard.CheckStartCast" },
		{ 211146, 0x18CCA88, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterSummon.CheckStartCast" },
		{ 211154, 0x18CCC00, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterStagger.CheckStartCast" },
		{ 211166, 0x18CCD38, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterDisarm.CheckStartCast" },
		{ 211176, 0x18CCED0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterCloak.CheckStartCast" },
		{ 211186, 0x18CD048, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterLight.CheckStartCast" },
		{ 211200, 0x18CD1E0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterInvisibility.CheckStartCast" },
		{ 211210, 0x18CD358, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterBoundItem.CheckStartCast" },
		{ 211232, 0x18CD668, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterTargetEffect.CheckStartCast" },
		{ 211270, 0x18CD9E0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterParalyze.CheckStartCast" },
		{ 211276, 0x18CDB78, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterScript.CheckStartCast" },
		{ 211973, 0x18D5318, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterReanimate.CheckStartCast" },
		{ 211706, 0x18D0FF0, 0x0, 0, {  }, "CombatStyle.MagicOffensive.CheckShouldEquip" },
		{ 211612, 0x18D0570, 0x0, 0, {  }, "CombatStyle.MagicRestore.CheckShouldEquip" },
		{ 211658, 0x18D0AB0, 0x0, 0, {  }, "CombatStyle.MagicWard.CheckShouldEquip" },
		{ 211568, 0x18D0010, 0x0, 0, {  }, "CombatStyle.MagicSummon.CheckShouldEquip" },
		{ 211524, 0x18CFAF0, 0x0, 0, {  }, "CombatStyle.MagicStagger.CheckShouldEquip" },
		{ 211480, 0x18CF590, 0x0, 0, {  }, "CombatStyle.MagicDisarm.CheckShouldEquip" },
		{ 211436, 0x18CF070, 0x0, 0, {  }, "CombatStyle.MagicCloak.CheckShouldEquip" },
		{ 211390, 0x18CEB30, 0x0, 0, {  }, "CombatStyle.MagicLight.CheckShouldEquip" },
		{ 211346, 0x18CE5D0, 0x0, 0, {  }, "CombatStyle.MagicInvisibility.CheckShouldEquip" },
		{ 211302, 0x18CE070, 0x0, 0, {  }, "CombatStyle.MagicBoundItem.CheckShouldEquip" },
		{ 211204, 0x18CD410, 0x0, 0, {  }, "CombatStyle.MagicTargetEffect.CheckShouldEquip" },
		{ 211092, 0x18CC518, 0x0, 0, {  }, "CombatStyle.MagicParalyze.CheckShouldEquip" },
		{ 211050, 0x18CBF80, 0x0, 0, {  }, "CombatStyle.MagicScript.CheckShouldEquip" },
		{ 211148, 0x18CCC78, 0x0, 0, {  }, "CombatStyle.MagicReanimate.CheckShouldEquip" },
		{ 211254, 0x18CDA98, 0x0, 0, {  }, "CombatStyle.MagicArmor.CheckShouldEquip" },
		{ 211688, 0x18D0DF0, 0x0, 0, {  }, "CombatStyle.StaffOffensive.CheckShouldEquip" },
		{ 211608, 0x18D03F0, 0x0, 0, {  }, "CombatStyle.StaffRestore.CheckShouldEquip" },
		{ 211642, 0x18D08B0, 0x0, 0, {  }, "CombatStyle.StaffWard.CheckShouldEquip" },
		{ 211552, 0x18CFE10, 0x0, 0, {  }, "CombatStyle.StaffSummon.CheckShouldEquip" },
		{ 211508, 0x18CF8F0, 0x0, 0, {  }, "CombatStyle.StaffStagger.CheckShouldEquip" },
		{ 211464, 0x18CF390, 0x0, 0, {  }, "CombatStyle.StaffDisarm.CheckShouldEquip" },
		{ 211420, 0x18CEE70, 0x0, 0, {  }, "CombatStyle.StaffCloak.CheckShouldEquip" },
		{ 211380, 0x18CE950, 0x0, 0, {  }, "CombatStyle.StaffLight.CheckShouldEquip" },
		{ 211330, 0x18CE390, 0x0, 0, {  }, "CombatStyle.StaffInvisibility.CheckShouldEquip" },
		{ 211284, 0x18CDE50, 0x0, 0, {  }, "CombatStyle.StaffBoundItem.CheckShouldEquip" },
		{ 211182, 0x18CD100, 0x0, 0, {  }, "CombatStyle.StaffTargetEffect.CheckShouldEquip" },
		{ 211076, 0x18CC2A0, 0x0, 0, {  }, "CombatStyle.StaffParalyze.CheckShouldEquip" },
		{ 211034, 0x18CBD80, 0x0, 0, {  }, "CombatStyle.StaffScript.CheckShouldEquip" },
		{ 211128, 0x18CC948, 0x0, 0, {  }, "CombatStyle.StaffReanimate.CheckShouldEquip" },
		{ 211234, 0x18CD800, 0x0, 0, {  }, "CombatStyle.StaffArmor.CheckShouldEquip" },
		{ 68617, 0xCD8F40, 0x0, 0, {  }, "Board.PollInputDevices" },
		{ 68545, 0xCD5650, 0x0, 0, {  }, "Board.ToggleControls" },
		{ 25052, 0x3CDEE0, 0x0, 0, {  }, "Packages.ForceRefTo" },
		{ 38561, 0x6B6930, 0x0, 0, {  }, "Probe.StartCombat" },
		{ 68233, 0xCC90C0, 0x0, 0, {  }, "CommonLib.BSReadWriteLock.LockForRead" },
		{ 68239, 0xCC9380, 0x0, 0, {  }, "CommonLib.BSReadWriteLock.UnlockForRead" },
		{ 40056, 0x717800, 0xA1, 15, { 0x48, 0x8B, 0x05, 0x00, 0x33, 0xA6, 0x02, 0x8B, 0x88, 0x40, 0x03, 0x00, 0x00, 0xD1, 0xE9 }, "Actuation.SummonCap.AddCommandedActor" },
		{ 403330, 0x317ABA8, 0x0, 0, {  }, "Actuation.SummonCap.SkipFlagGlobal" },
	};

	// 1.5.97.0: 55 rows
	inline constexpr REL::SelfCheck::Row kRows_1_5_97[] = {
		{ 261397, 0x165DA40, 0x0, 0, {  }, "Targeting.Character.UpdateCombat" },
		{ 261916, 0x16635E0, 0x0, 0, {  }, "MainThread.PlayerCharacter.Update" },
		{ 257613, 0x1637490, 0x0, 0, {  }, "CasterConsent.ActorMagicCaster.CheckCast" },
		{ 265003, 0x1686CA0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterOffensive.CheckStartCast" },
		{ 265007, 0x1686DC8, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterRestore.CheckStartCast" },
		{ 265005, 0x1686D38, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterWard.CheckStartCast" },
		{ 265009, 0x1686E60, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterSummon.CheckStartCast" },
		{ 265011, 0x1686EF0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterStagger.CheckStartCast" },
		{ 265013, 0x1686F88, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterDisarm.CheckStartCast" },
		{ 265015, 0x1687018, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterCloak.CheckStartCast" },
		{ 265017, 0x16870A8, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterLight.CheckStartCast" },
		{ 265019, 0x1687138, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterInvisibility.CheckStartCast" },
		{ 265021, 0x16871D0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterBoundItem.CheckStartCast" },
		{ 265025, 0x16872F8, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterTargetEffect.CheckStartCast" },
		{ 265029, 0x1687428, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterParalyze.CheckStartCast" },
		{ 265031, 0x16874C0, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterScript.CheckStartCast" },
		{ 265027, 0x1687390, 0x0, 0, {  }, "CasterConsent.CombatMagicCasterReanimate.CheckStartCast" },
		{ 265385, 0x168E628, 0x0, 0, {  }, "CombatStyle.MagicOffensive.CheckShouldEquip" },
		{ 265375, 0x168DEA8, 0x0, 0, {  }, "CombatStyle.MagicRestore.CheckShouldEquip" },
		{ 265380, 0x168E268, 0x0, 0, {  }, "CombatStyle.MagicWard.CheckShouldEquip" },
		{ 265370, 0x168DAE8, 0x0, 0, {  }, "CombatStyle.MagicSummon.CheckShouldEquip" },
		{ 265365, 0x168D728, 0x0, 0, {  }, "CombatStyle.MagicStagger.CheckShouldEquip" },
		{ 265360, 0x168D368, 0x0, 0, {  }, "CombatStyle.MagicDisarm.CheckShouldEquip" },
		{ 265355, 0x168CFA8, 0x0, 0, {  }, "CombatStyle.MagicCloak.CheckShouldEquip" },
		{ 265350, 0x168CBE8, 0x0, 0, {  }, "CombatStyle.MagicLight.CheckShouldEquip" },
		{ 265345, 0x168C828, 0x0, 0, {  }, "CombatStyle.MagicInvisibility.CheckShouldEquip" },
		{ 265340, 0x168C468, 0x0, 0, {  }, "CombatStyle.MagicBoundItem.CheckShouldEquip" },
		{ 265330, 0x168BCE8, 0x0, 0, {  }, "CombatStyle.MagicTargetEffect.CheckShouldEquip" },
		{ 265320, 0x168B568, 0x0, 0, {  }, "CombatStyle.MagicParalyze.CheckShouldEquip" },
		{ 265315, 0x168B1A8, 0x0, 0, {  }, "CombatStyle.MagicScript.CheckShouldEquip" },
		{ 265325, 0x168B928, 0x0, 0, {  }, "CombatStyle.MagicReanimate.CheckShouldEquip" },
		{ 265335, 0x168C0A8, 0x0, 0, {  }, "CombatStyle.MagicArmor.CheckShouldEquip" },
		{ 265383, 0x168E4A8, 0x0, 0, {  }, "CombatStyle.StaffOffensive.CheckShouldEquip" },
		{ 265373, 0x168DD28, 0x0, 0, {  }, "CombatStyle.StaffRestore.CheckShouldEquip" },
		{ 265378, 0x168E0E8, 0x0, 0, {  }, "CombatStyle.StaffWard.CheckShouldEquip" },
		{ 265368, 0x168D968, 0x0, 0, {  }, "CombatStyle.StaffSummon.CheckShouldEquip" },
		{ 265363, 0x168D5A8, 0x0, 0, {  }, "CombatStyle.StaffStagger.CheckShouldEquip" },
		{ 265358, 0x168D1E8, 0x0, 0, {  }, "CombatStyle.StaffDisarm.CheckShouldEquip" },
		{ 265353, 0x168CE28, 0x0, 0, {  }, "CombatStyle.StaffCloak.CheckShouldEquip" },
		{ 265348, 0x168CA68, 0x0, 0, {  }, "CombatStyle.StaffLight.CheckShouldEquip" },
		{ 265343, 0x168C6A8, 0x0, 0, {  }, "CombatStyle.StaffInvisibility.CheckShouldEquip" },
		{ 265338, 0x168C2E8, 0x0, 0, {  }, "CombatStyle.StaffBoundItem.CheckShouldEquip" },
		{ 265328, 0x168BB68, 0x0, 0, {  }, "CombatStyle.StaffTargetEffect.CheckShouldEquip" },
		{ 265318, 0x168B3E8, 0x0, 0, {  }, "CombatStyle.StaffParalyze.CheckShouldEquip" },
		{ 265313, 0x168B028, 0x0, 0, {  }, "CombatStyle.StaffScript.CheckShouldEquip" },
		{ 265323, 0x168B7A8, 0x0, 0, {  }, "CombatStyle.StaffReanimate.CheckShouldEquip" },
		{ 265333, 0x168BF28, 0x0, 0, {  }, "CombatStyle.StaffArmor.CheckShouldEquip" },
		{ 67315, 0xC150B0, 0x0, 0, {  }, "Board.PollInputDevices" },
		{ 67245, 0xC11C60, 0x0, 0, {  }, "Board.ToggleControls" },
		{ 24523, 0x375050, 0x0, 0, {  }, "Packages.ForceRefTo" },
		{ 37608, 0x6251B0, 0x0, 0, {  }, "Probe.StartCombat" },
		{ 66976, 0xC072D0, 0x0, 0, {  }, "CommonLib.BSReadWriteLock.LockForRead" },
		{ 66982, 0xC07590, 0x0, 0, {  }, "CommonLib.BSReadWriteLock.UnlockForRead" },
		{ 38993, 0x683D70, 0x51, 15, { 0x48, 0x8B, 0x05, 0x30, 0x29, 0x8A, 0x02, 0x8B, 0x88, 0x40, 0x03, 0x00, 0x00, 0xD1, 0xE9 }, "Actuation.SummonCap.AddCommandedActor" },
		{ 516851, 0x2F266F8, 0x0, 0, {  }, "Actuation.SummonCap.SkipFlagGlobal" },
	};

	inline constexpr REL::SelfCheck::Table kTables[] = {
		{ REL::Version(1, 6, 1170, 0), kRows_1_6_1170, std::size(kRows_1_6_1170) },
		{ REL::Version(1, 5, 97, 0), kRows_1_5_97, std::size(kRows_1_5_97) },
	};
}
